language: rust
sudo: false
cache: cargo

rust:
- stable
- beta
- nightly

script:
- cargo test
- cargo test --all-features

matrix:
  include:
  - rust: 1.13.0
    os: linux
    script:
    - cargo test

  - rust: 1.13.0
    os: osx
    script:
    - cargo test

  - name: clippy
    rust: nightly-2018-09-08
    install:
    - rustup component add clippy-preview
    script:
    - cargo clippy --all-targets -- -D warnings
    - touch src/lib.rs
    - cargo clippy --all-targets --all-features -- -D warnings

branches:
  only:
  - staging
  - trying
  - master
