language: rust

rust:
- stable
- beta
- nightly

script:
- cargo test
- cargo test --all-features

matrix:
  include:
  - os: osx

  - name: clippy
    install:
    - rustup component add clippy
    script:
    - cargo clippy --lib --tests --examples -- -D warnings
    - cargo clippy --lib --tests --examples --all-features -- -D warnings

branches:
  only:
  - staging
  - trying
  - master
