[package]
name = "bs58"
version = "0.1.2"
authors = ["Wim Looman <wim@nemo157.com>"]

description = "Another Base58 codec implementation."

repository = "https://github.com/mycorrhiza/bs58-rs"

readme = "README.md"
keywords = ["base58"]

license = "MIT/Apache-2.0"

[dev_dependencies]
base58 = "0.1.0"
rust-base58 = "0.0.4"
